FROM ubuntu:20.04
MAINTAINER Erik van Zijst <erik.van.zijst@gmail.com>
LABEL Description="Embedded AVR GNU C compiler"

RUN apt-get update -y
RUN apt-get install -y build-essential git gcc-avr avr-libc avrdude usbutils
